import { useEffect, useMemo, useState } from 'react';
import { Alert, Button, Descriptions, Form, Input, InputNumber, Select, Space, Spin, Steps, Table, Tabs, Typography, message } from 'antd';
import CodeMirror from '@uiw/react-codemirror';
import { sql } from '@codemirror/lang-sql';
import { autocompletion, type CompletionContext } from '@codemirror/autocomplete';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { analyzeManagedSql, createManagedTask, getManagedTask, listAvailableRealtimeTables, listMysqlTables, listServers, updateManagedTask } from '../api';
import type { ManagedTaskSave, ManagedTaskType, RealtimeServer, RealtimeTable } from '../types';

const defaults = (taskType: ManagedTaskType): ManagedTaskSave => ({ taskType, name: '', owner: '1', description: '', flinkVersion: '2.2.1', alarmConfig: {}, flinkConf: { parallelism: 1, checkpointIntervalSeconds: 60, taskManagerMemoryGb: 2, jobManagerMemoryGb: 1, flinkConfOverrides: {} }, taskConfig: taskType === 'compute' ? { computeConfig: { defaultDatabase: '', sql: '' } } : { exportConfig: { sourceDatabase: '', targetServerId: undefined as unknown as number, mappings: [], sink: { batchSize: 500, flushIntervalMs: 2000, maxRetries: 3 } } } });
export default function RealtimeManagedTaskEditorPage({ taskType }: { taskType: ManagedTaskType }) {
  const { taskId } = useParams(); const navigate = useNavigate(); const location = useLocation(); const id = taskId ? Number(taskId) : undefined; const label = taskType === 'compute' ? '计算' : '出仓';
  const routeState = location.state as { returnTo?: string; taskName?: string } | null;
  const returnTo = routeState?.returnTo || `/realtime/${taskType}`;
  const [form] = Form.useForm<ManagedTaskSave>(); const [step, setStep] = useState(0); const [mode, setMode] = useState<'wizard' | 'advanced'>('wizard'); const [loading, setLoading] = useState(false); const [supportLoading, setSupportLoading] = useState(true); const [supportError, setSupportError] = useState(''); const [tables, setTables] = useState<RealtimeTable[]>([]); const [servers, setServers] = useState<RealtimeServer[]>([]); const [mysqlTables, setMysqlTables] = useState<string[]>([]); const [plan, setPlan] = useState(''); const [metadataVisible, setMetadataVisible] = useState(true);
  const availableDatabases = useMemo(() => Array.from(new Set(tables.map((table) => table.databaseName))), [tables]);
  const sqlExtensions = useMemo(() => [sql(), autocompletion({ override: [(context: CompletionContext) => { const word = context.matchBefore(/[\w.`]+/); if (!word && !context.explicit) return null; return { from: word?.from ?? context.pos, options: tables.map((table) => ({ label: `paimon.${table.databaseName}.${table.tableName}`, type: 'class', detail: '受管实时表' })) }; }] })], [tables]);
  useEffect(() => {
    let active = true; setSupportLoading(true); setSupportError('');
    const taskRequest = id ? getManagedTask(id) : Promise.resolve(undefined);
    void Promise.all([listAvailableRealtimeTables(), listServers(), taskRequest]).then(([tableRows, serverRows, task]) => {
      if (!active) return; setTables(tableRows); setServers(serverRows);
      form.setFieldsValue(task ? { ...task, expectedUpdateTime: task.updateTime } : defaults(taskType));
    }).catch((error) => { if (active) setSupportError((error as Error).message); }).finally(() => { if (active) setSupportLoading(false); });
    return () => { active = false; };
  }, [form, id, taskType]);
  const taskName = Form.useWatch('name', form); const serverId = Form.useWatch(['taskConfig', 'exportConfig', 'targetServerId'], form); const sourceDatabase = Form.useWatch(['taskConfig', 'exportConfig', 'sourceDatabase'], form);
  useEffect(() => { const server = servers.find((item) => item.id === serverId); if (!server?.databaseName) { setMysqlTables([]); return; } void listMysqlTables(server.id, server.databaseName).then(setMysqlTables).catch((error) => message.error((error as Error).message)); }, [serverId, servers]);
  const submit = async () => { try { setLoading(true); const value = await form.validateFields(); if (id) await updateManagedTask(id, value); else await createManagedTask(value); message.success(`${label}任务已保存`); navigate(returnTo, { replace: true }); } catch (error) { if (error instanceof Error) message.error(error.message); } finally { setLoading(false); } };
  const analyze = async () => { try { await form.validateFields([['taskConfig', 'computeConfig', 'defaultDatabase'], ['taskConfig', 'computeConfig', 'sql']]); const value = form.getFieldsValue(true); const result = await analyzeManagedSql({ ...value, taskId: id }); setPlan(`${result.plan}\n输入：${result.inputs.join('、')}\n输出：${result.outputs.join('、')}`); message.success('SQL 校验通过'); } catch (error) { message.error(error instanceof Error ? error.message : '请检查 SQL 配置'); } };
  const common = <Descriptions bordered size="small" column={2} colon={false} className="realtime-config-table"><Descriptions.Item label="任务名称"><Form.Item name="name" rules={[{ required: true, message: '请输入任务名称' }]} noStyle><Input placeholder={`请输入${label}任务名称`} /></Form.Item></Descriptions.Item><Descriptions.Item label="负责人"><Form.Item name="owner" rules={[{ required: true, message: '请输入负责人' }]} noStyle><Input placeholder="请输入负责人" /></Form.Item></Descriptions.Item><Descriptions.Item label="描述" span={2}><Form.Item name="description" noStyle><Input.TextArea rows={3} placeholder="请输入任务用途和数据范围" /></Form.Item></Descriptions.Item><Descriptions.Item label="Flink 版本" span={2}><Form.Item name="flinkVersion" rules={[{ required: true }]} noStyle><Select disabled options={[{ value: '2.2.1', label: '2.2.1' }]} /></Form.Item></Descriptions.Item></Descriptions>;
  const alarm = <Descriptions bordered size="small" column={2} colon={false} className="realtime-config-table"><Descriptions.Item label="告警类型"><Form.Item name={['alarmConfig', 'alarmType']} noStyle><Select allowClear options={[{ value: 'failure', label: '失败告警' }, { value: 'all', label: '全部告警' }]} /></Form.Item></Descriptions.Item><Descriptions.Item label="告警组"><Form.Item name={['alarmConfig', 'alarmGroup']} noStyle><Input placeholder="输入告警接收组" /></Form.Item></Descriptions.Item></Descriptions>;
  const compute = <><Space className="managed-sql-toolbar"><Form.Item name={['taskConfig', 'computeConfig', 'defaultDatabase']} label="默认 Paimon 数据库" rules={[{ required: true }]}><Select style={{ width: 260 }} options={availableDatabases.map((value) => ({ value, label: value }))} /></Form.Item><Button onClick={() => setMetadataVisible((value) => !value)}>{metadataVisible ? '隐藏元数据' : '显示元数据'}</Button></Space><div className="managed-sql-layout">{metadataVisible && <aside className="managed-sql-metadata"><Typography.Text strong>受管实时表</Typography.Text><Typography.Paragraph type="secondary">拖动右边缘调整宽度</Typography.Paragraph>{tables.map((table) => <div key={table.id} className="managed-sql-table-item">{table.databaseName}.{table.tableName}</div>)}</aside>}<div className="managed-sql-editor"><Form.Item name={['taskConfig', 'computeConfig', 'sql']} rules={[{ required: true }]} noStyle><CodeMirror height="420px" extensions={sqlExtensions} basicSetup={{ lineNumbers: true, foldGutter: true, bracketMatching: true }} /></Form.Item></div></div><Space style={{ marginTop: 12 }}><Button onClick={() => void analyze()}>SQL 校验 / Explain</Button><Typography.Text type="secondary" style={{ whiteSpace: 'pre-line' }}>{plan}</Typography.Text></Space></>;
  const exportFields = <><div className="managed-task-form-grid"><Form.Item name={['taskConfig', 'exportConfig', 'sourceDatabase']} label="Paimon 源数据库" rules={[{ required: true }]}><Select options={availableDatabases.map((value) => ({ value, label: value }))} /></Form.Item><Form.Item name={['taskConfig', 'exportConfig', 'targetServerId']} label="目标 MySQL Server" rules={[{ required: true }]}><Select options={servers.map((item) => ({ value: item.id, label: `${item.name} / ${item.databaseName}` }))} /></Form.Item></div><Form.List name={['taskConfig', 'exportConfig', 'mappings']}>{(fields, { add, remove }) => <><Table rowKey="key" pagination={false} dataSource={fields} columns={[{ title: '受管实时表', render: (_, field) => <Form.Item name={[field.name, 'realtimeTableId']} rules={[{ required: true }]} noStyle><Select style={{ width: 320 }} options={tables.filter((table) => !sourceDatabase || table.databaseName === sourceDatabase).map((table) => ({ value: table.id, label: `${table.databaseName}.${table.tableName}` }))} /></Form.Item> }, { title: 'MySQL 目标表', render: (_, field) => <Form.Item name={[field.name, 'targetTable']} rules={[{ required: true }]} noStyle><Select showSearch style={{ width: 260 }} options={mysqlTables.map((value) => ({ value, label: value }))} /></Form.Item> }, { title: '操作', width: 90, render: (_, field) => <Button type="link" danger onClick={() => remove(field.name)}>删除</Button> }]} /><Button block type="dashed" onClick={() => add({ columnMappings: [] })}>添加表映射</Button></>}</Form.List></>;
  const resources = <Descriptions bordered size="small" column={2} colon={false} className="realtime-config-table"><Descriptions.Item label="并行度"><Form.Item name={['flinkConf', 'parallelism']} rules={[{ required: true }]} noStyle><InputNumber min={1} max={128} style={{ width: '100%' }} /></Form.Item></Descriptions.Item><Descriptions.Item label="Checkpoint 间隔"><Form.Item name={['flinkConf', 'checkpointIntervalSeconds']} rules={[{ required: true }]} noStyle><InputNumber min={10} max={600} addonAfter="秒" style={{ width: '100%' }} /></Form.Item></Descriptions.Item><Descriptions.Item label="TaskManager 内存"><Form.Item name={['flinkConf', 'taskManagerMemoryGb']} noStyle><InputNumber min={1} addonAfter="GB" style={{ width: '100%' }} /></Form.Item></Descriptions.Item><Descriptions.Item label="JobManager 内存"><Form.Item name={['flinkConf', 'jobManagerMemoryGb']} noStyle><InputNumber min={1} addonAfter="GB" style={{ width: '100%' }} /></Form.Item></Descriptions.Item>{taskType === 'export' && <><Descriptions.Item label="MySQL 批量行数"><Form.Item name={['taskConfig', 'exportConfig', 'sink', 'batchSize']} noStyle><InputNumber min={1} style={{ width: '100%' }} /></Form.Item></Descriptions.Item><Descriptions.Item label="刷新间隔"><Form.Item name={['taskConfig', 'exportConfig', 'sink', 'flushIntervalMs']} noStyle><InputNumber min={100} addonAfter="ms" style={{ width: '100%' }} /></Form.Item></Descriptions.Item><Descriptions.Item label="最大重试" span={2}><Form.Item name={['taskConfig', 'exportConfig', 'sink', 'maxRetries']} noStyle><InputNumber min={0} max={10} style={{ width: '100%' }} /></Form.Item></Descriptions.Item></>}</Descriptions>;
  const sections = [
    { title: '基础信息', description: `定义${label}任务的名称、负责人和基础属性`, content: common },
    { title: '告警配置', description: `配置${label}任务异常时的告警方式`, content: alarm },
    { title: taskType === 'compute' ? 'SQL 编辑' : '出仓设置', description: taskType === 'compute' ? '编辑受管 Flink SQL 并校验输入、输出实时表' : '选择受管实时表与已有 MySQL 目标表', content: taskType === 'compute' ? compute : exportFields },
    { title: '资源与运行', description: '设置 Flink 资源、Checkpoint 与运行参数', content: resources },
  ];
  const sectionContent = (section: typeof sections[number]) => <div className="realtime-editor-panel"><div className="realtime-editor-panel-title"><Typography.Title level={5}>{section.title}</Typography.Title><Typography.Text type="secondary">{section.description}</Typography.Text></div><div className="realtime-editor-section">{section.content}</div></div>;
  return <div className="realtime-sync-editor-page">
    <header className="realtime-sync-editor-page-header"><div><Typography.Title level={4}>{id ? `编辑${label}任务${taskName || routeState?.taskName ? ` · ${taskName || routeState?.taskName}` : ''}` : `新建实时${label}任务`}</Typography.Title><Typography.Text type="secondary">{taskType === 'compute' ? '受管实时表 → Flink SQL → 受管实时表' : '受管实时表 → MySQL 已有表'}</Typography.Text></div><Space><Button onClick={() => navigate(returnTo)}>返回任务列表</Button><Button type="primary" disabled={Boolean(supportError)} loading={loading} onClick={() => void submit()}>{id ? '保存修改' : '保存'}</Button></Space></header>
    <div className="realtime-sync-editor-page-body"><Spin spinning={supportLoading}>{supportError && <Alert type="error" showIcon message={`${label}任务加载失败`} description={supportError} className="realtime-editor-warning" />}
      <Tabs className="realtime-editor-mode-tabs ui-flat-tabs" activeKey={mode} items={[{ key: 'wizard', label: '分步向导' }, { key: 'advanced', label: '高级配置' }]} onChange={(value) => setMode(value as 'wizard' | 'advanced')} />
      <Form form={form} layout="vertical" preserve disabled={Boolean(supportError)}>{mode === 'wizard' ? <div className="realtime-wizard"><Steps direction="vertical" current={step} items={sections.map((item) => ({ title: item.title }))} onChange={setStep} /><div className="realtime-wizard-content">{sectionContent(sections[step])}<div className="realtime-wizard-actions"><Button disabled={step === 0} onClick={() => setStep((value) => value - 1)}>上一步</Button>{step < sections.length - 1 ? <Button type="primary" onClick={() => void form.validateFields().then(() => setStep((value) => value + 1))}>下一步</Button> : <Button type="primary" disabled={Boolean(supportError)} loading={loading} onClick={() => void submit()}>{id ? '保存修改' : '保存'}</Button>}</div></div></div>
        : <div className="realtime-advanced-content">{sections.map((item) => <section className="realtime-advanced-section" key={item.title}>{sectionContent(item)}</section>)}<div className="realtime-advanced-actions"><Button type="primary" disabled={Boolean(supportError)} loading={loading} onClick={() => void submit()}>{id ? '保存修改' : '保存'}</Button></div></div>}</Form>
    </Spin></div>
  </div>;
}
