import { useCallback, useEffect, useState } from 'react';
import { Button, Descriptions, Form, Input, InputNumber, Modal, Select, Space, Table, Tabs, Tag, Tooltip, Typography, message } from 'antd';
import { CopyOutlined, PlusOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons';
import { createRealtimeTable, getRealtimeTable, listRealtimeDatabases, listRealtimeTables, refreshRealtimeTable, safeUpdateRealtimeTable } from '../api';
import type { RealtimeTable, RealtimeTableColumn } from '../types';
import { useAutoTableActionWidth } from '../../utils/useAutoTableActionWidth';
import { createRealtimeTableDdl } from '../utils/realtimeTableDdl';

const typeOptions = ['BOOLEAN', 'TINYINT', 'SMALLINT', 'INT', 'BIGINT', 'FLOAT', 'DOUBLE', 'STRING', 'BYTES', 'DATE', 'TIMESTAMP(3)', 'DECIMAL(18,2)'].map((value) => ({ value, label: value }));
const statusLabel: Record<string, string> = { declared: '待创建', active: '可用', error: '异常' };
const statusColor: Record<string, string> = { declared: 'processing', active: 'success', error: 'error' };

export default function RealtimeTablesPage() {
  const { actionColumnWidth, actionRef } = useAutoTableActionWidth({ initialWidth: 190, minWidth: 150 });
  const [rows, setRows] = useState<RealtimeTable[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(false);
  const [keyword, setKeyword] = useState(''); const [status, setStatus] = useState('all'); const [source, setSource] = useState('all'); const [producer, setProducer] = useState(''); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20);
  const [databases, setDatabases] = useState<string[]>([]); const [editing, setEditing] = useState(false); const [detail, setDetail] = useState<RealtimeTable>(); const [detailLoading, setDetailLoading] = useState(false);
  const detailDdl = detail?.ddl || createRealtimeTableDdl(detail);
  const [addColumn, setAddColumn] = useState(false); const [form] = Form.useForm(); const [columnForm] = Form.useForm();
  const load = useCallback(async () => { setLoading(true); try { const query = new URLSearchParams({ page: String(page), pageSize: String(pageSize) }); if (keyword) query.set('keyword', keyword); if (status !== 'all') query.set('status', status); if (source !== 'all') query.set('source', source); if (producer) query.set('producer', producer); const result = await listRealtimeTables(query); setRows(result.records); setTotal(result.total); } catch (error) { message.error((error as Error).message); } finally { setLoading(false); } }, [keyword, page, pageSize, producer, source, status]);
  useEffect(() => { void load(); void listRealtimeDatabases().then(setDatabases).catch(() => setDatabases([])); }, [load]);
  const openDetail = async (id: number) => { setDetailLoading(true); try { setDetail(await getRealtimeTable(id)); } catch (error) { message.error((error as Error).message); } finally { setDetailLoading(false); } };
  const openSafeUpdate = async (id: number) => { try { const table = await getRealtimeTable(id); setDetail(table); columnForm.setFieldsValue({ comment: table.tableComment, options: { 'snapshot.time-retained': table.options?.['snapshot.time-retained'], 'compaction.min.file-num': table.options?.['compaction.min.file-num'] }, addColumns: [], columnComments: [] }); setAddColumn(true); } catch (error) { message.error((error as Error).message); } };
  const submit = async () => { try { const value = await form.validateFields(); await createRealtimeTable({ ...value, comment: value.tableComment, columns: value.columns, options: { bucket: String(value.bucket ?? 2), 'changelog-producer': value.changelogProducer } }); message.success('实时表已创建'); setEditing(false); form.resetFields(); await load(); } catch (error) { if (error instanceof Error) message.error(error.message); } };
  const refresh = async (row: RealtimeTable) => { try { await refreshRealtimeTable(row.id); message.success('物理表状态已刷新'); await load(); if (detail?.id === row.id) await openDetail(row.id); } catch (error) { message.error((error as Error).message); } };
  const copyDdl = async () => { if (!detailDdl) return; try { await navigator.clipboard.writeText(detailDdl); message.success('建表 DDL 已复制'); } catch { message.error('复制失败，请手动选择建表 DDL'); } };
  const create = () => { form.setFieldsValue({ tableType: 'primary_key', bucket: 2, changelogProducer: 'input', columns: [{ nullable: false, primaryKey: true, partitionKey: false }] }); setEditing(true); };
  return <div className="realtime-page realtime-sync-tasks-page realtime-tables-page"><section className="realtime-sync-main-panel">
    <div className="realtime-sync-filter-section"><div className="realtime-table-toolbar">
      <div className="realtime-table-filter-row"><Input value={keyword} onChange={(e) => setKeyword(e.target.value)} onPressEnter={() => { setPage(1); void load(); }} prefix={<SearchOutlined />} placeholder="库名 / 表名 / 描述" allowClear /><Select value={status} onChange={setStatus} options={[{ value: 'all', label: '全部状态' }, { value: 'active', label: '可用' }, { value: 'declared', label: '待创建' }, { value: 'error', label: '异常' }]} /><Select value={source} onChange={setSource} options={[{ value: 'all', label: '全部来源' }, { value: 'manual', label: '手工创建' }, { value: 'sync', label: '同步任务' }]} /><Input value={producer} onChange={(e) => setProducer(e.target.value)} placeholder="生产任务 ID / 名称" allowClear /><Button type="primary" icon={<SearchOutlined />} onClick={() => { setPage(1); void load(); }}>查询</Button><Typography.Text type="secondary" className="realtime-table-total">共 {total} 张</Typography.Text></div>
      <Space size={8}><Tooltip title="刷新"><Button aria-label="刷新" icon={<ReloadOutlined />} onClick={() => void load()} /></Tooltip><Tooltip title="新建实时表"><Button aria-label="新建实时表" type="primary" icon={<PlusOutlined />} onClick={create} /></Tooltip></Space>
    </div></div>
    <div className="realtime-sync-table-section"><Table rowKey="id" loading={loading} dataSource={rows} scroll={{ x: 1170 + actionColumnWidth }} pagination={{ current: page, pageSize, total, showSizeChanger: true, pageSizeOptions: [20, 50, 100], showTotal: (value) => `共 ${value} 张` }} onChange={(pagination) => { setPage(pagination.current || 1); setPageSize(pagination.pageSize || 20); }} columns={[
      { title: '实时表', width: 420, fixed: 'left', render: (_, row) => <Button type="link" onClick={() => void openDetail(row.id)}>{row.databaseName}.{row.tableName}</Button> },
      { title: '类型', width: 130, render: (_, row) => row.tableType === 'primary_key' ? '主键表' : 'Append-only' },
      { title: '状态', width: 110, render: (_, row) => <Tag color={statusColor[row.physicalStatus]}>{statusLabel[row.physicalStatus] || row.physicalStatus}</Tag> },
      { title: '来源', width: 120, render: (_, row) => row.creationSource === 'sync' ? '同步任务' : '手工创建' },
      { title: '生产任务', width: 260, ellipsis: true, render: (_, row) => row.producerTaskName || '-' }, { title: '字段 / 引用', width: 130, render: (_, row) => `${row.columnCount ?? 0} / ${row.referenceCount ?? 0}` },
      { title: '操作', width: actionColumnWidth, fixed: 'right', className: 'table-operation-column', render: (_, row) => <div ref={actionRef(row.id)} className="table-row-actions"><Space><Button type="link" onClick={() => void openDetail(row.id)}>详情</Button><Button type="link" onClick={() => void refresh(row)}>刷新</Button>{row.creationSource === 'manual' && <Button type="link" onClick={() => void openSafeUpdate(row.id)}>安全变更</Button>}</Space></div> },
    ]} /></div>
    <Modal title="新建实时表" open={editing} width={980} onCancel={() => setEditing(false)} onOk={() => void submit()} destroyOnHidden>
      <Form form={form} layout="vertical"><Space align="start" wrap><Form.Item name="databaseName" label="Paimon 数据库" rules={[{ required: true }]}><Select style={{ width: 220 }} options={databases.map((value) => ({ value, label: value }))} /></Form.Item><Form.Item name="tableName" label="表名" rules={[{ required: true }, { pattern: /^[A-Za-z_][A-Za-z0-9_]{0,127}$/ }]}><Input style={{ width: 240 }} /></Form.Item><Form.Item name="tableType" label="表类型" rules={[{ required: true }]}><Select style={{ width: 180 }} options={[{ value: 'primary_key', label: '主键表' }, { value: 'append_only', label: 'Append-only' }]} /></Form.Item><Form.Item name="bucket" label="Bucket"><InputNumber min={-1} /></Form.Item><Form.Item name="changelogProducer" label="Changelog"><Select style={{ width: 160 }} options={['none', 'input', 'lookup', 'full-compaction'].map((value) => ({ value, label: value }))} /></Form.Item></Space><Form.Item name="tableComment" label="表描述"><Input /></Form.Item><Form.List name="columns">{(fields, { add, remove }) => <><Table pagination={false} dataSource={fields} rowKey="key" columns={[{ title: '字段名', render: (_, field) => <Form.Item name={[field.name, 'name']} rules={[{ required: true }]} noStyle><Input /></Form.Item> }, { title: '数据类型', render: (_, field) => <Form.Item name={[field.name, 'dataType']} rules={[{ required: true }]} noStyle><Select options={typeOptions} showSearch /></Form.Item> }, { title: '可空', width: 100, render: (_, field) => <Form.Item name={[field.name, 'nullable']} noStyle><Select options={[{ value: true, label: '是' }, { value: false, label: '否' }]} /></Form.Item> }, { title: '主键', width: 100, render: (_, field) => <Form.Item name={[field.name, 'primaryKey']} noStyle><Select options={[{ value: false, label: '否' }, { value: true, label: '是' }]} /></Form.Item> }, { title: '分区键', width: 100, render: (_, field) => <Form.Item name={[field.name, 'partitionKey']} noStyle><Select options={[{ value: false, label: '否' }, { value: true, label: '是' }]} /></Form.Item> }, { title: '描述', render: (_, field) => <Form.Item name={[field.name, 'comment']} noStyle><Input /></Form.Item> }, { title: '', width: 60, render: (_, field) => <Button type="link" danger onClick={() => remove(field.name)}>删除</Button> }]} /><Button block type="dashed" icon={<PlusOutlined />} onClick={() => add({ nullable: true, primaryKey: false, partitionKey: false })}>添加字段</Button></>}</Form.List></Form>
    </Modal>
    <Modal title={detail ? `${detail.databaseName}.${detail.tableName}` : '实时表详情'} open={Boolean(detail) && !addColumn} onCancel={() => setDetail(undefined)} footer={null} width={980}><Tabs className="ui-flat-tabs realtime-table-detail-tabs" items={[
      { key: 'detail', label: '表详情', children: <><Descriptions bordered size="small" column={2}><Descriptions.Item label="状态"><Tag color={detail && statusColor[detail.physicalStatus]}>{detail && statusLabel[detail.physicalStatus]}</Tag></Descriptions.Item><Descriptions.Item label="来源">{detail?.creationSource === 'sync' ? '同步任务自动登记' : '实时表管理创建'}</Descriptions.Item><Descriptions.Item label="生产任务">{detail?.producerTaskName || '-'}</Descriptions.Item><Descriptions.Item label="最近同步">{detail?.lastSyncedAt || '-'}</Descriptions.Item><Descriptions.Item label="描述" span={2}>{detail?.tableComment || '-'}</Descriptions.Item></Descriptions><Typography.Title level={5}>字段</Typography.Title><Table size="small" pagination={false} rowKey="name" dataSource={detail?.columns} columns={[{ title: '字段', dataIndex: 'name' }, { title: '类型', dataIndex: 'dataType' }, { title: '可空', render: (_, row: RealtimeTableColumn) => row.nullable ? '是' : '否' }, { title: '主键', render: (_, row: RealtimeTableColumn) => row.primaryKey ? '是' : '-' }, { title: '分区', render: (_, row: RealtimeTableColumn) => row.partitionKey ? '是' : '-' }, { title: '描述', dataIndex: 'comment' }]} /><Typography.Title level={5}>任务依赖</Typography.Title><Table size="small" pagination={false} rowKey={(row) => `${row.taskId}-${row.referenceRole}`} dataSource={detail?.dependencies} columns={[{ title: '任务', dataIndex: 'taskName' }, { title: '类型', dataIndex: 'taskType' }, { title: '角色', dataIndex: 'referenceRole' }, { title: '状态', dataIndex: 'status' }]} /></> },
      { key: 'ddl', label: '建表 DDL', children: <div className="realtime-table-ddl-panel"><div className="realtime-table-ddl-toolbar"><Typography.Text type="secondary">完整 Paimon CREATE TABLE 语句</Typography.Text><Space><Button icon={<ReloadOutlined />} loading={detailLoading} onClick={() => detail && void openDetail(detail.id)}>重新读取</Button><Button icon={<CopyOutlined />} disabled={!detailDdl} onClick={() => void copyDdl()}>复制 DDL</Button></Space></div>{detailDdl ? <pre>{detailDdl}</pre> : <div className="realtime-table-ddl-empty">{detail?.ddlError || '未读取到 Paimon 物理表结构'}</div>}</div> },
    ]} /></Modal>
    <Modal title="安全变更" open={addColumn} width={760} onCancel={() => setAddColumn(false)} onOk={async () => { try { const value = await columnForm.validateFields(); if (!detail) return; await safeUpdateRealtimeTable(detail.id, value); message.success('安全变更已应用'); setAddColumn(false); await load(); } catch (error) { if (error instanceof Error) message.error(error.message); } }}><Form form={columnForm} layout="vertical"><Form.Item name="comment" label="表描述"><Input /></Form.Item><Space><Form.Item name={['options', 'snapshot.time-retained']} label="快照保留时间"><Input placeholder="例如 1 d" /></Form.Item><Form.Item name={['options', 'compaction.min.file-num']} label="Compaction 最小文件数"><Input placeholder="例如 5" /></Form.Item></Space><Typography.Text strong>修改字段描述</Typography.Text><Form.List name="columnComments">{(fields, { add, remove }) => <><Space direction="vertical" style={{ width: '100%', marginTop: 8 }}>{fields.map((field) => <Space key={field.key}><Form.Item name={[field.name, 'name']} rules={[{ required: true }]}><Select style={{ width: 220 }} options={detail?.columns?.map((column) => ({ value: column.name, label: column.name }))} placeholder="已有字段" /></Form.Item><Form.Item name={[field.name, 'comment']}><Input style={{ width: 300 }} placeholder="字段描述" /></Form.Item><Button type="link" danger onClick={() => remove(field.name)}>删除</Button></Space>)}</Space><Button type="dashed" onClick={() => add()}>修改字段描述</Button></>}</Form.List><Typography.Text strong style={{ display: 'block', marginTop: 18 }}>增加可空字段</Typography.Text><Form.List name="addColumns">{(fields, { add, remove }) => <><Space direction="vertical" style={{ width: '100%', marginTop: 8 }}>{fields.map((field) => <Space key={field.key}><Form.Item name={[field.name, 'name']} rules={[{ required: true }]}><Input placeholder="新增字段名" /></Form.Item><Form.Item name={[field.name, 'dataType']} rules={[{ required: true }]}><Select style={{ width: 180 }} options={typeOptions} placeholder="类型" /></Form.Item><Form.Item name={[field.name, 'nullable']}><Select style={{ width: 100 }} options={[{ value: true, label: '可空' }]} /></Form.Item><Button type="link" danger onClick={() => remove(field.name)}>删除</Button></Space>)}</Space><Button type="dashed" onClick={() => add({ nullable: true })}>增加字段</Button></>}</Form.List></Form></Modal>
  </section></div>;
}
