CREATE TABLE IF NOT EXISTS sql_task (
  id                     BIGINT        NOT NULL AUTO_INCREMENT COMMENT '任务ID，数据库自增主键',
  name                   VARCHAR(128)  NOT NULL COMMENT '任务名称',
  description            VARCHAR(1024) NULL COMMENT '任务描述',
  task_type              VARCHAR(32)   NOT NULL DEFAULT 'RUN_HIVE' COMMENT '任务类型',
  execution_frequency    VARCHAR(128)  NOT NULL DEFAULT '手动执行' COMMENT '执行频率描述',
  owner                  VARCHAR(64)   NOT NULL COMMENT '负责人',
  enabled                TINYINT(1)    NOT NULL DEFAULT 1 COMMENT '任务状态：0停用，1启用',
  sql_content            LONGTEXT      NOT NULL COMMENT '当前生效 Hive SQL',
  ddl_content            LONGTEXT      NULL COMMENT '当前生效的表结构变更 DDL，仅保存不自动执行',
  parameter_schema       LONGTEXT      NULL COMMENT '类型化运行参数定义 JSON',
  sql_checksum           CHAR(64)      NOT NULL COMMENT '当前生效代码 SHA-256 校验和',
  revision               BIGINT        NOT NULL DEFAULT 1 COMMENT '任务乐观锁版本号',
  effective_version_no   INT           NULL COMMENT '当前生效版本号；初始代码未由版本生效时为空',
  archived               TINYINT(1)    NOT NULL DEFAULT 0 COMMENT '是否归档：0否，1是',
  archived_by            VARCHAR(20)   NULL COMMENT '归档操作人 obId',
  archived_time          DATETIME      NULL COMMENT '归档时间',
  created_by             VARCHAR(20)   NOT NULL COMMENT '创建人 obId',
  updated_by             VARCHAR(20)   NOT NULL COMMENT '最后更新人 obId',
  create_time            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  KEY idx_sql_task_status_time (archived, update_time),
  KEY idx_sql_task_enabled (enabled),
  KEY idx_sql_task_name (name),
  KEY idx_sql_task_updated_by (updated_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SQL Agent Hive 任务及当前生效代码';

CREATE TABLE IF NOT EXISTS sql_task_version (
  id                         BIGINT        NOT NULL AUTO_INCREMENT COMMENT '版本记录ID',
  task_id                    BIGINT        NOT NULL COMMENT '任务ID',
  version_no                 INT           NOT NULL COMMENT '任务内递增版本号，从1开始',
  base_effective_version_no  INT           NULL COMMENT '创建草稿时所基于的生效版本号',
  base_effective_checksum    CHAR(64)      NOT NULL COMMENT '创建草稿时生效代码SHA-256，用于基线校验',
  name                       VARCHAR(128)  NOT NULL COMMENT '版本内任务名称',
  description                VARCHAR(1024) NULL COMMENT '版本内任务描述',
  sql_content                LONGTEXT      NOT NULL COMMENT '版本草稿 Hive SQL',
  ddl_content                LONGTEXT      NULL COMMENT '版本内表结构变更 DDL，仅保存不自动执行',
  parameter_schema           LONGTEXT      NULL COMMENT '版本草稿类型化运行参数定义JSON',
  sql_checksum               CHAR(64)      NOT NULL COMMENT '版本草稿内容SHA-256',
  version_note               VARCHAR(512)  NOT NULL COMMENT '版本说明',
  status                     VARCHAR(16)   NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT、EFFECTIVE、HISTORICAL、STALE',
  revision                   BIGINT        NOT NULL DEFAULT 1 COMMENT '版本草稿乐观锁版本号',
  created_by                 VARCHAR(20)   NOT NULL COMMENT '创建人obId',
  updated_by                 VARCHAR(20)   NOT NULL COMMENT '最后更新人obId',
  effective_by               VARCHAR(20)   NULL COMMENT '生效操作人obId',
  effective_time             DATETIME      NULL COMMENT '生效时间',
  create_time                DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time                DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_version_no (task_id, version_no),
  KEY idx_task_version_time (task_id, update_time),
  KEY idx_task_version_status (task_id, status, update_time),
  KEY idx_task_version_base (task_id, base_effective_version_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SQL Agent Hive 可编辑版本草稿';

CREATE TABLE IF NOT EXISTS sql_task_version_step (
  id             BIGINT       NOT NULL AUTO_INCREMENT COMMENT '版本Step记录ID',
  task_id        BIGINT       NOT NULL COMMENT '任务ID',
  version_no     INT          NOT NULL COMMENT '任务版本号',
  step_no        INT          NOT NULL COMMENT '脚本中声明的Step编号',
  step_order     INT          NOT NULL COMMENT '脚本内执行顺序，从0开始',
  step_name      VARCHAR(128) NULL COMMENT 'Step显示名称',
  step_sql       LONGTEXT     NOT NULL COMMENT '版本草稿Step SQL',
  statement_type VARCHAR(32)  NOT NULL COMMENT 'SELECT、WITH、INSERT',
  input_tables   TEXT         NULL COMMENT '输入表 JSON 数组',
  output_tables  TEXT         NULL COMMENT '输出表 JSON 数组',
  sql_checksum   CHAR(64)     NOT NULL COMMENT 'Step SQL SHA-256 校验和',
  create_time    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_task_version_step_no (task_id, version_no, step_no),
  UNIQUE KEY uk_task_version_step_order (task_id, version_no, step_order),
  KEY idx_version_step_version (task_id, version_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SQL Agent 任务版本草稿Step表';

CREATE TABLE IF NOT EXISTS sql_task_execution (
  id                    BIGINT        NOT NULL AUTO_INCREMENT COMMENT '执行实例ID',
  task_id               BIGINT        NOT NULL COMMENT '任务ID',
  task_name_snapshot    VARCHAR(128)  NOT NULL COMMENT '提交时任务名称快照',
  sql_snapshot          LONGTEXT      NOT NULL COMMENT '提交时源 SQL 快照',
  parameter_schema_snapshot LONGTEXT  NULL COMMENT '提交时类型化参数定义 JSON 快照',
  rendered_sql_snapshot LONGTEXT      NULL COMMENT '参数渲染后的 SQL 快照',
  parameter_values      LONGTEXT      NULL COMMENT '本次运行参数 JSON',
  business_date         DATE          NULL COMMENT '旧日期表达式的计算基准日期',
  source_type           VARCHAR(16)   NOT NULL COMMENT '执行来源：EFFECTIVE、VERSION',
  task_version_no       INT           NULL COMMENT '执行版本号；未版本化的初始生效代码为空',
  task_revision         BIGINT        NULL COMMENT '执行生效代码时的任务revision',
  status                VARCHAR(16)   NOT NULL COMMENT 'PENDING、QUEUED、RUNNING、SUCCEEDED、FAILED、CANCELLING、CANCELLED',
  current_step_no       INT           NULL COMMENT '当前正在执行的Step编号',
  total_steps           INT           NOT NULL DEFAULT 0 COMMENT 'Step总数',
  succeeded_steps       INT           NOT NULL DEFAULT 0 COMMENT '成功Step数',
  failed_step_no        INT           NULL COMMENT '失败Step编号',
  requested_by          VARCHAR(20)   NOT NULL COMMENT '执行人 obId',
  executor_instance_id  VARCHAR(64)   NULL COMMENT 'Agent执行器实例ID',
  query_id              VARCHAR(256)  NULL COMMENT '最后一个Hive Query ID',
  application_ids       TEXT          NULL COMMENT 'YARN Application ID JSON数组',
  job_ids               TEXT          NULL COMMENT 'MapReduce Job ID JSON数组',
  error_message         VARCHAR(4000) NULL COMMENT '脱敏后的错误摘要',
  submitted_at          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '提交时间',
  started_at            DATETIME      NULL COMMENT '开始执行时间',
  finished_at           DATETIME      NULL COMMENT '结束时间',
  heartbeat_at          DATETIME      NULL COMMENT 'Agent最近心跳时间',
  update_time           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  KEY idx_task_execution_task_time (task_id, submitted_at),
  KEY idx_task_execution_status_time (status, update_time),
  KEY idx_task_execution_source (task_id, source_type, task_version_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SQL Agent Hive任务执行实例表';

CREATE TABLE IF NOT EXISTS sql_task_execution_step (
  id                    BIGINT        NOT NULL AUTO_INCREMENT COMMENT '执行Step记录ID',
  execution_id          BIGINT        NOT NULL COMMENT '执行实例ID',
  task_id               BIGINT        NOT NULL COMMENT '任务ID',
  step_no               INT           NOT NULL COMMENT '脚本中声明的Step编号',
  step_order            INT           NOT NULL COMMENT '执行顺序，从0开始',
  step_name             VARCHAR(128)  NULL COMMENT 'Step显示名称',
  source_sql_snapshot   LONGTEXT      NOT NULL COMMENT '参数渲染前Step SQL',
  rendered_sql_snapshot LONGTEXT      NOT NULL COMMENT '实际提交Hive的Step SQL',
  status                VARCHAR(16)   NOT NULL COMMENT 'PENDING、RUNNING、SUCCEEDED、FAILED、SKIPPED、CANCELLING、CANCELLED',
  query_id              VARCHAR(256)  NULL COMMENT 'Hive Query ID',
  application_ids       TEXT          NULL COMMENT 'YARN Application ID JSON数组',
  job_ids               TEXT          NULL COMMENT 'MapReduce Job ID JSON数组',
  error_message         VARCHAR(4000) NULL COMMENT '脱敏后的错误摘要',
  log_file              VARCHAR(512)  NULL COMMENT '相对日志文件路径',
  started_at            DATETIME      NULL COMMENT '开始时间',
  finished_at           DATETIME      NULL COMMENT '结束时间',
  update_time           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_execution_step_order (execution_id, step_order),
  UNIQUE KEY uk_execution_step_no (execution_id, step_no),
  KEY idx_execution_step_status (execution_id, status),
  KEY idx_execution_step_task (task_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SQL Agent Hive任务执行Step表';
